CREATE TABLE payments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          order_id BIGINT NOT NULL,

                          amount NUMERIC(19, 2) NOT NULL,

                          status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

                          transaction_reference VARCHAR(100),

                          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_payments_order
                              FOREIGN KEY (order_id)
                                  REFERENCES orders (id)
                                  ON DELETE CASCADE,

                          CONSTRAINT chk_payments_amount
                              CHECK (amount >= 0),

                          CONSTRAINT chk_payments_status
                              CHECK (
                                  status IN (
                                             'PENDING',
                                             'SUCCESS',
                                             'FAILED',
                                             'REFUNDED'
                                      )
                                  )
);

CREATE INDEX idx_payments_order_id
    ON payments (order_id);

CREATE INDEX idx_payments_status
    ON payments (status);