CREATE TABLE reviews (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         product_id BIGINT NOT NULL,
                         user_id BIGINT NOT NULL,

                         rating SMALLINT NOT NULL,
                         comment TEXT,

                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT fk_reviews_product
                             FOREIGN KEY (product_id)
                                 REFERENCES products (id)
                                 ON DELETE CASCADE,

                         CONSTRAINT fk_reviews_user
                             FOREIGN KEY (user_id)
                                 REFERENCES users (id)
                                 ON DELETE CASCADE,

                         CONSTRAINT chk_reviews_rating
                             CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_reviews_product_id
    ON reviews (product_id);

CREATE INDEX idx_reviews_user_id
    ON reviews (user_id);

CREATE INDEX idx_reviews_product_created_at
    ON reviews (product_id, created_at);