ALTER TABLE order_items
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE order_items
    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP;