CREATE TABLE addresses (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           user_id BIGINT NOT NULL,

                           title VARCHAR(100) NOT NULL,
                           country VARCHAR(100) NOT NULL,
                           city VARCHAR(100) NOT NULL,
                           postal_code VARCHAR(30) NOT NULL,
                           street VARCHAR(255) NOT NULL,
                           building VARCHAR(50),
                           unit VARCHAR(50),

                           is_default BOOLEAN NOT NULL DEFAULT FALSE,

                           created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT fk_addresses_user
                               FOREIGN KEY (user_id)
                                   REFERENCES users (id)
                                   ON DELETE CASCADE
);

CREATE INDEX idx_addresses_user_id
    ON addresses (user_id);