CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            parent_id BIGINT,

                            name VARCHAR(150) NOT NULL,
                            slug VARCHAR(180) NOT NULL,

                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT uk_categories_slug UNIQUE (slug),

                            CONSTRAINT fk_categories_parent
                                FOREIGN KEY (parent_id)
                                    REFERENCES categories (id)
                                    ON DELETE SET NULL
);

CREATE INDEX idx_categories_parent_id
    ON categories (parent_id);