CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          category_id BIGINT NOT NULL,

                          name VARCHAR(255) NOT NULL,
                          slug VARCHAR(280) NOT NULL,
                          description TEXT,

                          price NUMERIC(19, 2) NOT NULL,

                          sku VARCHAR(100) NOT NULL,

                          status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

                          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT uk_products_slug UNIQUE (slug),

                          CONSTRAINT uk_products_sku UNIQUE (sku),

                          CONSTRAINT fk_products_category
                              FOREIGN KEY (category_id)
                                  REFERENCES categories (id)
                                  ON DELETE RESTRICT,

                          CONSTRAINT chk_products_price
                              CHECK (price >= 0),

                          CONSTRAINT chk_products_status
                              CHECK (status IN ('ACTIVE', 'INACTIVE', 'OUT_OF_STOCK'))
);

CREATE INDEX idx_products_category_id
    ON products (category_id);

CREATE INDEX idx_products_status
    ON products (status);

CREATE INDEX idx_products_price
    ON products (price);