CREATE TABLE inventory (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           product_id BIGINT NOT NULL,

                           quantity INTEGER NOT NULL DEFAULT 0,
                           reserved_quantity INTEGER NOT NULL DEFAULT 0,

                           updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT uk_inventory_product UNIQUE (product_id),

                           CONSTRAINT fk_inventory_product
                               FOREIGN KEY (product_id)
                                   REFERENCES products (id)
                                   ON DELETE CASCADE,

                           CONSTRAINT chk_inventory_quantity
                               CHECK (quantity >= 0),

                           CONSTRAINT chk_inventory_reserved_quantity
                               CHECK (reserved_quantity >= 0),

                           CONSTRAINT chk_inventory_reserved_not_exceed_quantity
                               CHECK (reserved_quantity <= quantity)
);