CREATE TABLE carts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       user_id BIGINT NOT NULL,

                       created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT uk_carts_user UNIQUE (user_id),

                       CONSTRAINT fk_carts_user
                           FOREIGN KEY (user_id)
                               REFERENCES users (id)
                               ON DELETE CASCADE
);