CREATE TABLE coupons (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         code VARCHAR(50) NOT NULL,

                         type VARCHAR(30) NOT NULL,

                         value NUMERIC(19, 2) NOT NULL,

                         minimum_order_amount NUMERIC(19, 2) NOT NULL DEFAULT 0,
                         maximum_discount NUMERIC(19, 2),

                         start_date TIMESTAMP WITH TIME ZONE NOT NULL,
                         expiration_date TIMESTAMP WITH TIME ZONE NOT NULL,

                         usage_limit INTEGER,
                         used_count INTEGER NOT NULL DEFAULT 0,

                         active BOOLEAN NOT NULL DEFAULT TRUE,

                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT uk_coupons_code UNIQUE (code),

                         CONSTRAINT chk_coupons_type
                             CHECK (type IN ('PERCENTAGE', 'FIXED_AMOUNT')),

                         CONSTRAINT chk_coupons_value
                             CHECK (value >= 0),

                         CONSTRAINT chk_coupons_minimum_order_amount
                             CHECK (minimum_order_amount >= 0),

                         CONSTRAINT chk_coupons_maximum_discount
                             CHECK (maximum_discount IS NULL OR maximum_discount >= 0),

                         CONSTRAINT chk_coupons_usage_limit
                             CHECK (usage_limit IS NULL OR usage_limit >= 0),

                         CONSTRAINT chk_coupons_used_count
                             CHECK (used_count >= 0),

                         CONSTRAINT chk_coupons_usage_count
                             CHECK (
                                 usage_limit IS NULL
                                     OR used_count <= usage_limit
                                 ),

                         CONSTRAINT chk_coupons_dates
                             CHECK (expiration_date > start_date)
);

CREATE INDEX idx_coupons_active
    ON coupons (active);

CREATE INDEX idx_coupons_expiration_date
    ON coupons (expiration_date);