CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        order_number VARCHAR(50) NOT NULL,

                        user_id BIGINT NOT NULL,
                        coupon_id BIGINT,

                        status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

                        subtotal NUMERIC(19, 2) NOT NULL,
                        discount NUMERIC(19, 2) NOT NULL DEFAULT 0,
                        shipping_cost NUMERIC(19, 2) NOT NULL DEFAULT 0,
                        total NUMERIC(19, 2) NOT NULL,

                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT uk_orders_order_number
                            UNIQUE (order_number),

                        CONSTRAINT fk_orders_user
                            FOREIGN KEY (user_id)
                                REFERENCES users (id)
                                ON DELETE RESTRICT,

                        CONSTRAINT fk_orders_coupon
                            FOREIGN KEY (coupon_id)
                                REFERENCES coupons (id)
                                ON DELETE SET NULL,

                        CONSTRAINT chk_orders_status
                            CHECK (
                                status IN (
                                           'PENDING',
                                           'CONFIRMED',
                                           'PROCESSING',
                                           'SHIPPED',
                                           'DELIVERED',
                                           'CANCELLED'
                                    )
                                ),

                        CONSTRAINT chk_orders_subtotal
                            CHECK (subtotal >= 0),

                        CONSTRAINT chk_orders_discount
                            CHECK (discount >= 0),

                        CONSTRAINT chk_orders_shipping_cost
                            CHECK (shipping_cost >= 0),

                        CONSTRAINT chk_orders_total
                            CHECK (total >= 0)
);

CREATE INDEX idx_orders_user_id
    ON orders (user_id);

CREATE INDEX idx_orders_status
    ON orders (status);

CREATE INDEX idx_orders_created_at
    ON orders (created_at);

CREATE INDEX idx_orders_coupon_id
    ON orders (coupon_id);